hw 5: Coroutines
AlenaLaillusion/FundamentalsKotlin pull request #4
Opened 2020-12-19 09:41 UTC by AlenaLaillusion

hw 5  Coroutines

2020-12-23 15:48 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +       binding.rvActor.layoutManager =
форматирование по всем файлам

2020-12-23 15:49 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +            binding.tvReviews.text = reviews.toString() + "  " +  resources.getString(R.string.reviews_)
у тебя один пробел в ресурсах и один сама добавляешь - оставь пробел в ресурсах и сделай плейсхолдер там же

2020-12-23 15:49 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +            with(movie) {
форматирование

2020-12-23 15:50 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        binding.rvActor.adapter = ActorsAdapterDiffUtil()
лучше этот адаптер вынести в lateinit поле чем каждый раз кастить адаптер из рецайла

2020-12-23 15:50 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +            movie?.let { setMovieData(it) }
(this:: setMovieData) старайся минимально it использовать

2020-12-23 15:51 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +    val imageOption = RequestOptions()
поля пиши сверху над методами и почему оно публичное и зачем вообще выносить это в поле

2020-12-23 15:52 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +            binding.tvTag.text =  genres.joinToString(", ") { it.name }
(Genre::name)

2020-12-23 15:53 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +        SupervisorJob() +
+ переноси на новую строку чтобы понимать что добавила

2020-12-23 15:53 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +    //private var recycler: RecyclerView? = null
не надо оставлять закоментированный код

2020-12-23 15:53 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +            // send list into adapter
убери комментарии

2020-12-23 15:54 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +                moviesList?.let { bindMovies(it) }
(::bindMovies)

2020-12-23 15:55 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
>          var btnBack: TextView? = null
не используется

2020-12-23 15:56 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +        binding.rvMovie.hasFixedSize()
setHasFixedSize?

2020-12-23 15:57 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
>  const val  GRID_LAYOUT_ROW_COUNT = 2
константу лучше или в самом низу или верху обозначить или там где используется - но не где попало

2020-12-23 15:58 UTC, konstzv commented on app/src/main/res/layout/view_holder_movie.xml
> +        android:id="@+id/ratingStar"
может ratingBar

2020-12-23 15:58 UTC, konstzv commented on app/src/main/res/layout/fragment_movies_details.xml
> +            app:layout_constraintHorizontal_bias="0.0"
зачем?

2020-12-23 15:59 UTC, konstzv commented on app/src/main/res/values/styles.xml
> +    <style name="MyRatingBar2" parent="Theme.AppCompat">
называй более конкретными именами, почитай про наследование. стилей, можно не дублировать первый два атрибута

2020-12-23 16:00 UTC, konstzv requested changes
Поправь замечания, отформатируй весь код

2020-12-29 13:49 UTC, AlenaLaillusion reviewed
corrected comments

2021-01-04 10:33 UTC, merged