Hw 6 mvvm
AlenaLaillusion/FundamentalsKotlin pull request #5
Opened 2021-01-06 13:47 UTC by AlenaLaillusion

my HW 6: MVVM

2021-01-11 08:54 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/ActorsAdapterDiffUtil.kt
> +    private var actorsList = listOf<Actor>()
emptyList лучше используй

2021-01-11 08:56 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/ActorsAdapterDiffUtil.kt
>  class ActorViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
в отдельный класс вынеси

2021-01-11 08:56 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        binding.tvBack.apply {
apply лишний

2021-01-11 08:56 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        movie?.let { setMovieData(movie) }
(:: setMovieData)

2021-01-11 08:57 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        val movie = requireArguments().getParcelable<Movie>(Movie::class.java.simpleName)
лучше передавай id фильма

2021-01-11 08:57 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        with(movie) {
раздяй код на блоки - не пиши слитно

2021-01-11 08:58 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesDetails.kt
> +        super.onDetach()
лучше в другом порядке - onDetach в конце - там могут быть какие-то терминальные методы

2021-01-11 10:05 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +            // get movie list
убери комментарии - они должны быть только в крайнем случае в коде - если там что-то нетривиальное

2021-01-11 10:10 UTC, konstzv requested changes
поправь замечания

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +            (binding.rvMovie.adapter as? MoviesAdapter)?.apply {
apply лишний

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +                moviesList?.let { bindMovies(moviesList!!) }
!! использовать не надо - если метод вернул null то надо показать ошибку на ui

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +                Log.d("Parcel", "move.name = ${movie.title}")
для лога байндинги не нужны

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/MainActivity.kt
> +            .apply {
транзакция это билдер - apply не нужен - пиши все через точку

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/MoviesAdapter.kt
> +    private val clickListener: ClickListener?
оно у тебя null может быть?

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/MoviesAdapter.kt
> +class MoviesViewHolder(itemView: View) : RecyclerView.ViewHolder(itemView) {
в отдельный класс вынеси

2021-01-11 10:10 UTC, konstzv commented on app/src/main/java/com/example/fundamentalskotlin/MoviesAdapter.kt
> +        binding.ivLike.setImageResource(if (movie.like) R.drawable.ic_like_red else R.drawable.ic_like)
ну плохо же читается разнеси на несколько строк с if (){} else{}

2021-01-19 09:39 UTC, AlenaLaillusion commented
this is looking

2021-01-19 10:10 UTC, AlenaLaillusion reviewed
Fixed comments hw-6-MVVM

2021-01-24 16:21 UTC, konstzv commented
Отпиши в комментариях что исправила или resolved пометь их
Например в ActorsAdapterDiffUtil  list не заменила на emotyList
Откуда появился пакет package com.example.fundamentalskotlin ?

2021-02-01 09:09 UTC, AlenaLaillusion reviewed
fix

2021-02-04 14:16 UTC, AlenaLaillusion commented on app/src/main/java/com/example/fundamentalskotlin/FragmentMoviesList.kt
> +            (binding.rvMovie.adapter as? MoviesAdapter)?.apply {
resolve

2021-02-05 15:37 UTC, merged